from core.config import settings

BOT_NAME = "proteus"
SPIDER_MODULES = ["scraper.spiders"]
NEWSPIDER_MODULE = "scraper.spiders"
ROBOTSTXT_OBEY = False
DOWNLOAD_TIMEOUT = 20
CONCURRENT_REQUESTS = 8
LOG_LEVEL = settings.log_level.upper()
ITEM_PIPELINES = {
    "scraper.pipelines.StoragePipeline": 300,
}

SCRAPY_SETTINGS = {
    "BOT_NAME": BOT_NAME,
    "SPIDER_MODULES": SPIDER_MODULES,
    "NEWSPIDER_MODULE": NEWSPIDER_MODULE,
    "ROBOTSTXT_OBEY": ROBOTSTXT_OBEY,
    "DOWNLOAD_TIMEOUT": DOWNLOAD_TIMEOUT,
    "CONCURRENT_REQUESTS": CONCURRENT_REQUESTS,
    "LOG_LEVEL": LOG_LEVEL,
    "ITEM_PIPELINES": ITEM_PIPELINES,
}
